apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  Namespace: roboshop # if we dont give specific namespace it will take default namespac
spec: 
  containers:
  - name: nginx-simple
    image: nginx:1.14.2
    ports:
    - containerPort: 80